// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/channels": {
            "get": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "List SMS channels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin.ChannelResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Create an SMS channel",
                "parameters": [
                    {
                        "description": "Channel request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateChannelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.ChannelResponse"
                        }
                    }
                }
            }
        },
        "/sms": {
            "post": {
                "description": "Reserves credit and queues an asynchronous SMS delivery.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS"
                ],
                "summary": "Queue an SMS",
                "parameters": [
                    {
                        "description": "SMS request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerSMSRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerSMSResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/sms/{message_id}": {
            "get": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS Reports"
                ],
                "summary": "Get an SMS delivery report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SMS message ID",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SwaggerDeliveryReport"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "post": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Create a wallet",
                "parameters": [
                    {
                        "description": "Wallet request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/admin.WalletResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}": {
            "get": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Get a wallet balance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wallet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.WalletResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/sms": {
            "get": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMS Reports"
                ],
                "summary": "List SMS delivery reports for a wallet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wallet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum reports (1-500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.SwaggerDeliveryReport"
                            }
                        }
                    }
                }
            }
        },
        "/wallets/{id}/topup": {
            "post": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "Top up a wallet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wallet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Top-up request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.TopUpWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin.WalletResponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/transactions": {
            "get": {
                "security": [
                    {
                        "AdminAPIKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallets"
                ],
                "summary": "List wallet transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wallet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin.TransactionResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ChannelResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "integer"
                }
            }
        },
        "admin.CreateChannelRequest": {
            "type": "object",
            "required": [
                "name",
                "wallet_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "integer"
                }
            }
        },
        "admin.CreateWalletRequest": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                }
            }
        },
        "admin.TopUpWalletRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "reference_id": {
                    "type": "string"
                }
            }
        },
        "admin.TransactionResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reference_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "integer"
                }
            }
        },
        "admin.WalletResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.SwaggerDeliveryReport": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "channel": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "delivered_at": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "last_error": {
                    "type": "string"
                },
                "line": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "integer"
                }
            }
        },
        "handler.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.SwaggerSMSRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "main"
                },
                "dest": {
                    "type": "string",
                    "example": "989121234567"
                },
                "line": {
                    "type": "string",
                    "example": "express"
                },
                "message": {
                    "type": "string",
                    "example": "Your verification code is 123456"
                }
            }
        },
        "handler.SwaggerSMSResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "boolean"
                },
                "channel": {
                    "type": "string"
                },
                "cost": {
                    "type": "number"
                },
                "dest": {
                    "type": "string"
                },
                "line": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "remaining_balance": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminAPIKey": {
            "type": "apiKey",
            "name": "X-Admin-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SMS Gateway API",
	Description:      "Asynchronous SMS gateway with Redis credit reservations and delivery reports.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
